import { Box, Modal, ModalBody, ModalCloseButton, ModalContent, ModalOverlay, ModalProps, VStack } from "@chakra-ui/react";
import { ActionCreatorWithoutPayload } from "@reduxjs/toolkit";
import { useSelector, useDispatch } from 'react-redux'
import { AppState } from "../state";


export interface RaresamaModalProps extends Omit<ModalProps, 'isOpen' | 'children' | 'onClose'> {

    children?: React.ReactNode,
    title: string,

    //these are generated by redux rtk 
    closeActionCreator: ActionCreatorWithoutPayload<string>,
    isOpenSelector: (state: AppState) => boolean
    centerTitle?: boolean;
};


export const RaresamaModal: React.FC<RaresamaModalProps> = ({ children, title, closeActionCreator, isOpenSelector, centerTitle, ...rest }) => {

    const isOpen = useSelector(isOpenSelector)
    const dispatch = useDispatch()

    return (
        <Modal isOpen={isOpen} onClose={() => dispatch(closeActionCreator())} {...rest}>
            <ModalOverlay />
            <ModalContent>
                <ModalCloseButton />
                <ModalBody>
                    <VStack w="100%" h="100%" padding="26px 10px 16px 10px" spacing="0">
                        {!!title &&
                            <Box
                                w="100%"
                                textAlign={centerTitle ? 'center' : "left"}
                                fontSize="30px"
                                lineHeight="36px"
                                fontWeight="700"
                                color="purple.900"
                            >{title}</Box>
                        }
                        <Box h="32px"></Box>
                        <Box w="100%">{children}</Box>
                    </VStack>
                </ModalBody>
            </ModalContent>
        </Modal>
    );
};
