import { Box, HStack, Modal, ModalBody, ModalCloseButton, ModalContent, ModalOverlay, ModalProps, VStack } from "@chakra-ui/react";
import { ActionCreatorWithoutPayload } from "@reduxjs/toolkit";
import { ReactNode } from "react";
import { useSelector, useDispatch } from 'react-redux'
import { Icon } from "tabler-icons-react";
import { AppState } from "../../state";
import { ModalIcon } from "../MoonsamaModal/ModalIcon";


export interface MoonsamaModalProps {
    //these are generated by redux rtk 
    closeActionCreator: ActionCreatorWithoutPayload<string>,
    isOpenSelector: (state: AppState) => boolean

    title?: string,
    TitleTablerIcon?: Icon
    message?: string,
    bottomButtonText?: string,
    isBottomButtonDisabled?: boolean,
    onBottomButtonClick?: () => void,
    TablerIcon?: Icon,
    iconBackgroundColor?: string,
    iconColor?: string,
    closeOnOverlayClick?: boolean,
    closeable?: boolean,
    children?: ReactNode
};


export const ReduxModal: React.FC<MoonsamaModalProps> = ({ closeActionCreator, isOpenSelector, title, TitleTablerIcon, message, bottomButtonText, onBottomButtonClick, TablerIcon, iconBackgroundColor, iconColor, closeOnOverlayClick, closeable, children, isBottomButtonDisabled }) => {

    const isOpen = useSelector(isOpenSelector)
    const dispatch = useDispatch()

    return (
        <Modal isOpen={isOpen} onClose={() => dispatch(closeActionCreator())} isCentered closeOnOverlayClick={closeOnOverlayClick}>
            <ModalOverlay />
            <ModalContent>
                {(closeable !== false) && <ModalCloseButton />}
                <ModalBody>
                    <VStack alignItems="flex-start" marginTop="16px" marginBottom="16px" spacing="0">
                        {TablerIcon &&
                            <Box marginBottom="16px">
                                <ModalIcon TablerIcon={TablerIcon} backgroundColor={iconBackgroundColor ? iconBackgroundColor : "inherit"} iconColor={iconColor ? iconColor : "inherit"}></ModalIcon>
                            </Box>
                        }
                        {!!title &&
                            <HStack
                                spacing="0"
                                fontSize="16px"
                                lineHeight="24px"
                                paddingBottom="16px"
                            >
                                {TitleTablerIcon && <Box paddingRight="6px"><TitleTablerIcon color="var(--chakra-colors-teal-200)" size="21px"></TitleTablerIcon></Box>}
                                <Box >{title}</Box>

                            </HStack>
                        }
                        {!!message &&
                            <Box
                                fontSize="16px"
                                lineHeight="24px"
                                paddingBottom="16px"
                                fontFamily="Rubik"
                                color="whiteAlpha.700"
                            >
                                {message}
                            </Box>
                        }
                        <Box w="100%" h="100%" fontFamily={"Rubik"}>{children}</Box>
                        {bottomButtonText &&
                            <>
                                <Box paddingTop="16px"></Box>
                                <Box
                                    alignSelf="center"
                                    cursor={(isBottomButtonDisabled === true) ? "not-allowed" : "pointer"}
                                    lineHeight="24px"
                                    fontFamily="Rubik"
                                    color={(isBottomButtonDisabled === true) ? "whiteAlpha.400" : "whiteAlpha.700"}
                                    onClick={onBottomButtonClick}
                                >{bottomButtonText}</Box></>}
                    </VStack>
                </ModalBody>
            </ModalContent>
        </Modal>
    );
};
