name: oracle-ui-dev
on:
  workflow_dispatch
jobs:
  buid-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: set image tag env
        run: echo "IMAGE_TAG=$(echo moonsama/oracle-ui:$(git rev-parse --short HEAD)-$(date +%F-%H-%M))" >> $GITHUB_ENV  

      - name: Build Image
        run: |
          docker build \
          --build-arg REACT_APP_CHAIN_ID=${{ env.REACT_APP_CHAIN_ID }} \
          --build-arg REACT_APP_RPC_URL=${{ env.REACT_APP_RPC_URL }} \
          --build-arg REACT_APP_SUBGRAPH_URL=${{ env.REACT_APP_SUBGRAPH_URL }} \
          --build-arg REACT_APP_NFT_SUBGRAPH_URL=${{ env.REACT_APP_NFT_SUBGRAPH_URL }} \
          --build-arg REACT_APP_BACKEND_API_URL=${{ env.REACT_APP_BACKEND_API_URL }} \
          -t ${{ env.IMAGE_TAG }} -f packages/minecraft-oracle-ui/Dockerfile .
        env:
          REACT_APP_CHAIN_ID: 1285
          REACT_APP_RPC_URL: https://rpc.api.moonriver.moonbeam.network
          REACT_APP_SUBGRAPH_URL: https://moonriver-subgraph.moonsama.com/subgraphs/name/moonsama/marketplacev2
          REACT_APP_NFT_SUBGRAPH_URL: https://moonriver-subgraph.moonsama.com/subgraphs/name/moonsama/nft
          REACT_APP_BACKEND_API_URL: https://minecraft-metaverse-api-staging.moonsama.com/api/v1

      - name: Push Image
        run: docker push ${{ env.IMAGE_TAG }}
      - name: Trigger the deployment workflow
        run: |
          curl -X POST https://api.github.com/repos/moonsama/metaverse-bridge-oracles-monorepo-deployment/actions/workflows/oracle-ui-dev-deploy.yaml/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer ${{ secrets.GH_DEPLOY_TOKEN }}" \
          --data "{\"ref\":\"main\",\"inputs\":{ \"image_tag\":\"${{ env.IMAGE_TAG }}\" }}"